# site settings
title: Pratik Somaiya
subtitle: Resume
email: psomaiya17@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl:  # the subpath of your site, e.g. /blog
url: https://pratik-somaiya.github.io/ # the base hostname & protocol for your site
author: Pratik Somaiya
city: Pune
state: MH
zip_code: 411036
country: INDIA
phone: (+91) 9428349285

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/pratiksomaiya17
github_url: https://github.com/Pratik-Somaiya/Pratik-Somaiya.github.io
instagram_url: https://instagram.com/pratiks17
linkedin_url: https://www.linkedin.com/in/pratik-somaiya
twitter_url: https://twitter.com/pratik_somaiya

# build settings
markdown: kramdown

sass:
  style: compressed